<?php

/**
 * @file
 * Contains custom_default_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_default_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_default_content module.
    case 'help.page.custom_default_content':
      $output = '';
      $output .= '<h3>' . t('Custom Default Content') . '</h3>';
      $output .= '<p>' . t('Custom default content module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_default_content_theme() {
  return [
    'custom_default_content' => [
      'render element' => 'children',
    ],
  ];
}
