<?php

/**
 * @file
 * Contains sample_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function PREFIX_sample_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sample_content module.
    case 'help.page.PREFIX_sample_content':
      $output = '';
      $output .= '<h3>' . t('Sample Content') . '</h3>';
      $output .= '<p>' . t('A custom import sample content module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function PREFIX_sample_content_theme() {
  return [
    'PREFIX_sample_content' => [
      'render element' => 'children',
    ],
  ];
}
